"""empty message

Revision ID: 48f6ec58fe67
Revises: 
Create Date: 2020-12-12 20:53:23.523798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f6ec58fe67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_callout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_known_latitude', sa.Float(), nullable=True),
    sa.Column('last_known_longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_path', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('member_of_path_id', sa.Integer(), nullable=True),
    sa.Column('number_within_path', sa.Integer(), nullable=True),
    sa.Column('is_last_point_in_path', sa.Boolean(), nullable=True),
    sa.Column('time_due_to_arrive', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waypoint')
    op.drop_table('response_unit')
    op.drop_table('path')
    op.drop_table('callout')
    # ### end Alembic commands ###
